import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@radix-ui/themes/styles.css';
import '../styles/theme-config.css';
import './globals.css';

import React from 'react';
import { SessionProvider } from 'next-auth/react';
import Navbar from '../components/navbar/Navbar';

import { Container, Theme } from '@radix-ui/themes';
import { auth } from '@/auth';

import ReactQueryClientProvider from '@/contexts/ReactQueryProvider ';
import { Toaster } from 'react-hot-toast';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Issue-tracker-api',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.variable}>
          <ReactQueryClientProvider>
            <Theme accentColor="violet">
              <Navbar />

              <main className="p-5">
                <Container>{children}</Container>
              </main>
            </Theme>
            <Toaster position="top-right" />
          </ReactQueryClientProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
